Dino
lframosferreira/bevy-games pull request #13
Opened 2023-08-08 20:45 UTC by lframosferreira

Jogo do dinossauro do chrome implementado. De forma geral, o jogo funciona bem, mas ainda não imlpementa coisas importantes como animações dos dinossauros ao se movimentar (bater de asas do ptera e pézinhos do Trex).

A sprite do T rex agachado tá com um sombreamento estranho em vola dela que não consegui identificar a origem, mas não é anda que prejudique jogabilidade, só visual.

Um ponto a se atentar é a lógica de colisão desse jogo, que também interfere nos outros. Em jogos como o Snake a colisao entre Sprites "perfeitas" (quadrados, retângulos, etc) é bem trivial. Aqui, a colisão deveria ser feita nos pixels em que as entidades existem de fato, não nesse quadrado da Sprite. No entanto, isso não ocorre, gerando situações estranhas em que aparentemente não há colisão, mas há sim um overlap de sprites. 

Não sei se o Bevy já tem uma implementação pra lidar com isso. No PyGame, tinha um conceito de máscaras pra tratar esse tipo de problema. Segue o link:
https://www.pygame.org/docs/ref/mask.html

2023-08-09 12:32 UTC, igorlfs commented
Alguém não gosta de instalar hooks de pre-commit

2023-08-09 13:10 UTC, igorlfs requested changes
Você poderia trocar o título da janela pra "Bevy Dinosaur"? A cor de fundo fica meio ruim com a crate common, mas depois mudo isso

2023-08-09 13:10 UTC, igorlfs commented on dino/src/game/cloud/mod.rs
> +use self::systems::*;
Deixa os módulos em cima, tira o self (infelizmente o cargo fmt não padroniza isso)

2023-08-09 13:10 UTC, igorlfs commented on dino/src/game/cloud/systems.rs
> +
remover essa linha (e formatar) pro `cargo fmt` organizar

2023-08-09 13:10 UTC, igorlfs commented on dino/src/game/dinosaur/resources.rs
> +#[derive(Resource)]
Deriva o Default

2023-08-09 13:10 UTC, igorlfs commented on dino/src/game/dinosaur/systems.rs
> +            if keyboard_input.just_pressed(KeyCode::Space) && !dino_down.is_down {
Usa else if ao invés de fazer um if dentro do else

2023-08-09 13:10 UTC, igorlfs commented on dino/src/game/dinosaur/systems.rs
>              }
O comportamento atual disso é incrementar a pontuação a cada frame que não existe colisão, para cada obstáculo. É realmente isso que a gente quer fazer? É mais parecido com o jogo original do dino (em comparação ao flappy bird, que a gente só aumenta a pontuação em 1, a cada objeto que fica pra trás), mas acho que tem jeitos melhores de fazer uma pontuação contínua -- por exemplo, ter um recurso que conta o tempo desde que o início do jogo (tratar restart e quit)

2023-08-09 13:10 UTC, igorlfs commented on dino/src/systems.rs
>  }
Não é melhor essas funções ficarem nos seus respectivos módulos?

2023-08-09 13:10 UTC, igorlfs commented on dino/src/systems.rs
> +            transform: dinosaur_transform.clone(),
```suggestion
            transform: *dinosaur_transform,
```

2023-08-09 13:21 UTC, igorlfs requested changes

2023-08-09 13:21 UTC, igorlfs commented on dino/src/game/score/mod.rs
> +            .add_systems(OnEnter(AppState::InGame), insert_score);
Isso tem um bug herdado do snake: ao pausar o jogo, o score é resetado. No snake isso foi corrigido em #12 e a ideia é só inserir no evento de Startup.

2023-08-10 10:17 UTC, igorlfs requested changes

2023-08-10 10:17 UTC, igorlfs commented on dino/src/game/cloud/mod.rs
> +use systems::*;
```suggestion
use bevy::prelude::*;
use common::*;
use resources::*;
use systems::*;
```

2023-08-10 10:17 UTC, igorlfs commented on dino/src/game/cloud/systems.rs
> +    cloud_spawn_timer.timer.tick(time.delta());
A gente poderia introduzir alguma aleatoriedade gerando um número aleatório e verificando se ele é menor que um limite.

2023-08-10 10:17 UTC, igorlfs commented on dino/src/game/cloud/systems.rs
> +}
```suggestion
pub fn despawn_clouds_over_time(
    mut commands: Commands,
    cloud_query: Query<(&Transform, Entity), With<Cloud>>,
) {
    for (cloud_transform, cloud_entity) in cloud_query.iter() {
        if cloud_transform.translation.x < 0.0 {
            commands.entity(cloud_entity).despawn();
        }
    }
}
```

Evite usar variáveis mutáveis (se não for necessário)

2023-08-10 10:17 UTC, igorlfs commented on dino/src/game/dinosaur/mod.rs
> +pub mod components;
```suggestion
mod components;
```
Agora esse módulo não precisa ser público

2023-08-10 10:17 UTC, igorlfs commented on dino/src/game/dinosaur/systems.rs
> +            let obstacle_dimensions: Vec2 = assets.get(obstacle_image_handle).unwrap().size();
```suggestion
            let dinosaur_dimensions = assets.get(dinosaur_image_handle).unwrap().size();
            let obstacle_dimensions = assets.get(obstacle_image_handle).unwrap().size();
```
Não anote tipos que podem ser inferidos

2023-08-10 10:17 UTC, igorlfs commented on dino/src/game/dinosaur/systems.rs
> +                dino_down.is_down = true;
Você precisa resetar o `is_down` quando o jogo reiniciar, porque se você morrer agachado, não vai conseguir pular (tente).

2023-08-10 10:17 UTC, igorlfs commented on dino/src/game/dinosaur/systems.rs
> +    if let Ok(dinosaur_entity) = dinosaur_query.get_single_mut() {
```suggestion
    dinosaur_query: Query<Entity, With<Dinosaur>>,
    keyboard_input: Res<Input<KeyCode>>,
    asset_server: Res<AssetServer>,
    dinosaur_vertical_movement: Res<DinoVerticalMovement>,
    mut dino_down: ResMut<DinoDown>,
) {
    if let Ok(dinosaur_entity) = dinosaur_query.get_single() {
```

2023-08-10 10:17 UTC, igorlfs commented on dino/src/game/dinosaur/systems.rs
> +            transform: dinosaur_transform.clone(),
```suggestion
            transform: *dinosaur_transform,
```

2023-08-10 10:17 UTC, igorlfs commented on dino/src/game/mod.rs
> +pub mod score;
Nenhum desses módulos precisa ser público

2023-08-10 10:17 UTC, igorlfs commented on dino/src/game/obstacle/mod.rs
>  use self::systems::*;
```suggestion
pub mod components;
mod resources;
mod systems;

use bevy::prelude::*;
use common::*;
use resources::{ObstacleSpawnTimer, ObstacleSpeed};
use systems::*;

const OBSTACLE_INITIAL_SPEED: f32 = 600.0;
const OBSTACLE_SPEED_INCREASE_RATE: f32 = 100.0;
```

2023-08-10 10:17 UTC, igorlfs commented on dino/src/game/obstacle/resources.rs
> +pub const OBSTACLE_SPAWN_TIME: f32 = 1.5;
```suggestion
use super::OBSTACLE_INITIAL_SPEED;
use bevy::prelude::*;

const OBSTACLE_SPAWN_TIME: f32 = 1.5;
```

2023-08-10 10:17 UTC, igorlfs commented on dino/src/game/obstacle/systems.rs
> +use crate::game::score::resources::Score;
```suggestion
use super::components::{Obstacle, ObstacleKind};
use super::resources::{ObstacleSpawnTimer, ObstacleSpeed};
use super::{OBSTACLE_INITIAL_SPEED, OBSTACLE_SPEED_INCREASE_RATE};
use crate::game::dinosaur::DINO_INITIAL_Y_POS;
use crate::game::score::resources::Score;
use bevy::prelude::*;
use bevy::window::PrimaryWindow;
use rand::rngs::ThreadRng;
use rand::Rng;
```

2023-08-10 10:17 UTC, igorlfs commented on dino/src/game/obstacle/systems.rs
> +        let mut rng: ThreadRng = rand::thread_rng();
Remova as anotações de tipo

2023-08-10 10:17 UTC, igorlfs commented on dino/src/game/score/resources.rs
> +use bevy::prelude::{Resource, Timer, TimerMode};
Acho que se a gente for usar mais de uma coisa do bevy, já compensa fazer o star import

2023-08-10 10:17 UTC, igorlfs commented on dino/src/game/score/resources.rs
> +            timer: Timer::from_seconds(SCORE_UPDATE_TIME, TimerMode::Repeating),
Talvez ficaria mais legal contar milissegundos (e dividir por alguma coisa)?

2023-08-10 10:17 UTC, igorlfs commented on dino/src/main.rs
>          .add_plugins(DebugLinesPlugin::default())
```suggestion
```
Não estamos usando as linhas nesse jogo

2023-08-10 10:17 UTC, igorlfs commented on dino/src/main.rs
```suggestion
const WINDOW_X: f32 = 1000.0;
const WINDOW_Y: f32 = 600.0;

```

2023-08-10 13:06 UTC, lframosferreira commented on dino/src/game/cloud/systems.rs
> +    cloud_spawn_timer.timer.tick(time.delta());
Mas porque?

2023-08-10 13:12 UTC, igorlfs commented on dino/src/game/cloud/systems.rs
> +    cloud_spawn_timer.timer.tick(time.delta());
Só pra introduzir um pouco de aleatoriedade

2023-08-10 14:46 UTC, lframosferreira commented on dino/src/game/cloud/systems.rs
> +    cloud_spawn_timer.timer.tick(time.delta());
Acho que fica um pouco de overkill ksksks

2023-08-13 15:17 UTC, igorlfs requested changes

2023-08-13 15:17 UTC, igorlfs commented on dino/src/game/obstacle/systems.rs
> +        let obstacle_width: f32 = assets.get(obstacle_handle_image).unwrap().size().x;
Esse unwrap pode causar um crash. Estava acontecendo comigo, mas não encontrei uma maneira confiável de reproduzir. De qualquer maneira, acho que é melhor evitar o `unwrap` e fazer um `if let Some(...) = `

2023-08-13 19:24 UTC, igorlfs approved these changes

2023-08-13 19:25 UTC, merged